export const PAGES = ['home', 'about', 'experience', 'skills', 'projects', 'contact']

export const DATA = {
  name: 'Christian Consuelo',
  role: 'Senior Software Engineer',
  location: 'Mexico City, MX',
  email: 'christian.consuelo2@gmail.com',
  linkedin: 'https://www.linkedin.com/in/cconsuelo',
  github: 'https://github.com/CrisTowi',
  tagline: 'Results-driven engineer with ten years of experience building impactful web applications, leading cross-functional teams, and overseeing technical architecture.',
  bio: [
    'I\'m a <strong>Senior Software Engineer</strong> with a decade of experience building products that matter — from fintech platforms to crypto trading tools, from recruiting systems to staff management ecosystems.',
    'I\'ve acted as a <strong>Directly Responsible Individual (DRI)</strong> on complex cross-functional initiatives, mentored engineers, and driven architectural decisions across large-scale technical environments.',
    'Expert in modern web frameworks and AI-assisted development tools like <strong>Cursor</strong> and <strong>Claude Code</strong>, I bring both technical depth and leadership breadth to every challenge.',
  ],
  interests: ['Videogames & interactive design', 'Fitness & movement', 'AI-assisted development', 'Open source contribution'],
  experience: [
    {
      company: 'Square (Block)',
      role: 'Senior Software Engineer',
      dates: 'May 2023 — Feb 2026',
      bullets: [
        'Specialized in the development and integration of staff management tools within complex, large-scale web ecosystems.',
        'Acted as DRI for major cross-functional projects, overseeing the entire lifecycle from strategic planning to technical execution.',
        'Coordinated efforts across multiple engineering teams to resolve architectural challenges and ensure seamless integration across core repositories.',
        'Mentored engineers and authored technical documentation to standardize best practices.',
      ],
    },
    {
      company: 'Bitso',
      role: 'Senior Frontend Engineer',
      dates: 'Sep 2020 — May 2023',
      bullets: [
        'Spearheaded the development of the Alpha trading platform, delivering high-performance tools for a major cryptocurrency exchange.',
        'Architected intuitive data visualizations and real-time data update streams to empower users with immediate market insights.',
        'Developed advanced technical analysis tools for sophisticated traders while building the Alpha Classic tool for novice users.',
      ],
    },
    {
      company: 'Zubale',
      role: 'Senior Software Engineer',
      dates: 'Oct 2019 — Sep 2020',
      bullets: [
        'Engineered a comprehensive client management platform as a Full-Stack developer, encompassing internal admin tools and external client dashboards.',
        'Constructed interactive data visualizations to provide actionable insights for client data management.',
        'Contributed to the architecture and implementation of a quest and task management system to optimize operational workflows.',
      ],
    },
    {
      company: 'Covalto',
      role: 'Senior Software Engineer',
      dates: 'Jan 2019 — Nov 2019',
      bullets: [
        'Developed a scalable internal platform to efficiently manage a high-volume portfolio of loans and leases.',
        'Built and maintained RESTful API services to provide secure and seamless data access to internal stakeholders.',
        'Designed and implemented user-friendly interfaces and data visualizations to facilitate data-driven decision-making.',
      ],
    },
    {
      company: 'Generation',
      role: 'Senior Software Engineer',
      dates: 'Aug 2016 — Dec 2018',
      bullets: [
        'Led the development, scaling, and technical strategy of a global recruiting platform used to impact thousands of students worldwide.',
        'Collaborated with cross-functional teams to deliver automated solutions that significantly optimized the recruitment lifecycle.',
        'Designed and maintained a complex, multi-language, highly scalable platform utilizing advanced technologies.',
      ],
    },
    {
      company: 'Intelimétrica',
      role: 'Full Stack Web Developer',
      dates: 'Mar 2015 — Aug 2016',
      bullets: [
        'Developed full-stack web applications focusing on highly interactive client-side interfaces and robust server-side logic.',
        'Managed non-relational database architectures using MongoDB.',
        'Created dynamic user interfaces and data visualizations using React.js and D3.js.',
      ],
    },
  ],
  projects: [
    {
      name: 'Recruitify',
      slug: 'recruitify',
      category: 'Web App',
      type: 'ui',
      featured: true,
      tagline: 'Job hunt tracker with AI interview simulation',
      description: 'A kanban-style tool for managing your entire job search — track companies, move applications through stages, log interviews, and simulate real interviews using AI with voice-to-text.',
      tech: ['React', 'Kanban', 'AI', 'Voice-to-text'],
      live: 'https://recruitify-black.vercel.app/',
      github: 'https://github.com/CrisTowi/Recruitify',
    },
    {
      name: 'GymBro',
      slug: 'gymbro',
      category: 'PWA',
      type: 'ui',
      featured: true,
      tagline: 'Your training partner in your pocket',
      description: 'A Progressive Web App for planning and tracking gym routines. Design your weekly plan, customize exercises, and run live sessions tracking sets, reps, weights, and rest timers.',
      tech: ['PWA', 'React', 'Node.js', 'REST API'],
      live: 'https://gymbro-roan.vercel.app/',
      github: 'https://github.com/CrisTowi/gymbro',
    },
    {
      name: 'Node Record',
      slug: 'noderecord',
      category: 'Visualization',
      type: 'ui',
      featured: false,
      tagline: 'Explore sample genealogies as an interactive map',
      description: 'A music discovery tool that maps sampling relationships between songs. Select a track and explore its entire sample tree — who sampled it and what it samples — as an interactive radial graph.',
      tech: ['React', 'D3.js', 'Graph visualization', 'Music API'],
      live: 'https://node-record.netlify.app/',
      github: 'https://github.com/CrisTowi/samplemap',
    },
    {
      name: 'Interview Sim',
      slug: 'interviewsim',
      category: 'Claude Skill',
      type: 'cli',
      featured: false,
      tagline: 'AI-powered hands-on coding interview simulator',
      description: 'A Claude Code skill that scaffolds a real coding challenge for interview prep — it creates a repo, seeds bugs or feature specs, and walks you through a simulated technical interview.',
      tech: ['Claude Code', 'AI', 'Shell scripting', 'GitHub API'],
      live: null,
      github: 'https://github.com/CrisTowi/claude-interview-sim',
    },
  ],
  skills: [
    {
      category: 'Leadership',
      title: 'Engineering Leadership',
      tags: ['Technical Leadership', 'Software Architecture', 'Engineering Mentorship', 'Cross-functional Coordination', 'DRI', 'Stakeholder Communication'],
    },
    {
      category: 'Languages & Frameworks',
      title: 'Frontend & Backend',
      tags: ['JavaScript', 'TypeScript', 'Python', 'Node.js', 'React.js', 'Next.js'],
    },
    {
      category: 'Infrastructure & Cloud',
      title: 'Cloud & DevOps',
      tags: ['AWS', 'Cloud Infrastructure Orchestration', 'Scalable Systems'],
    },
    {
      category: 'AI-Assisted Dev',
      title: 'AI & Automation',
      tags: ['Claude Code', 'Cursor', 'Amp', 'LLM API Integration'],
    },
    {
      category: 'Observability',
      title: 'Performance & Monitoring',
      tags: ['Datadog', 'Sentry', 'Core Web Vitals', 'Error Tracking'],
    },
    {
      category: 'Data & APIs',
      title: 'Data Systems',
      tags: ['RESTful APIs', 'RPC', 'SQL', 'MongoDB', 'Real-time Streams'],
    },
  ],
}
